// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "fireball":return img`
................................
................................
................................
................................
................................
................................
................................
................................
..............4444..............
............44455444............
...........3333444444...........
..........4f33322211f4..........
..........33ff3222ff54..........
.......55433ccf22fcc54455.......
.....55..433ca2244ca544..55.....
....5....44332244444444....5....
.....55..423c224444c444..55.....
.......55542ccc44ccc24555.......
..........555cccccc555..........
...........4255555524...........
............442cc244............
..............4444..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image1":
            case "Adventurer":return img`
dddddd22dddddddddddddd
d.....2222...........d
d......2222..........d
d.......2fffff.......d
d.......fffffff......d
d......fffffffff.....d
d......fff22222f.....d
d......fffff2fff.....d
d.......ffff2fff.....d
d......ccfff2ff.cc...d
d.....ccffafffaffcc..d
d....ccccffaaaffcccc.d
d....cfccfffafffccfc.d
d....ffffaffaffaffff.d
d...1fffffafffaffffffd
d...1ffffafacafafffffd
d...ffffffafcfaff1fffd
d..1fffffffacafff1ffff
d..1fff.cfffcfffc.ffff
d..ffff.fcfcfcfc..1fff
d..fff.1ffcfffcff..fff
d...ff.1fffffffff..ffd
d..f2f.ffffff1fff..f2f
d..f2f.ffff..ffff..f2f
d...ff.f1ff..f1ff..ffd
d......f1ff..f1ff....d
d......f1ff..f1ff....d
d.......ff....ff.....d
d2222..feeff.feeff...d
d.24444feeedffeeedf..d
d..2455caeeefcaeeef..d
dddd2455cfff55cfffdddd
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
